In [3]:
#기본적인 라이브러리와 데이터 불러오기

In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

train_target = pd.read_csv("sleep_data/training_label.csv")
test_target = pd.read_csv("sleep_data/val_label.csv")
train_input = pd.read_csv("sleep_data/train_sleep.csv")
test_input = pd.read_csv("sleep_data/val_sleep.csv")

In [5]:
#EMAIL에 대한 라벨링을 EMAIL로 통일

In [6]:
train_target = train_target.rename(columns={'SAMPLE_EMAIL':'EMAIL'})
train_target

                EMAIL DIAG_NM
0    nia+315@rowan.kr      CN
1    nia+014@rowan.kr     MCI
2    nia+220@rowan.kr      CN
3    nia+096@rowan.kr     MCI
4    nia+396@rowan.kr      CN
..                ...     ...
136  nia+181@rowan.kr      CN
137  nia+354@rowan.kr      CN
138  nia+448@rowan.kr     MCI
139  nia+394@rowan.kr      CN
140  nia+067@rowan.kr     Dem

[141 rows x 2 columns]

In [7]:
#데이터를 쉽게 구분하기 위해 이메일에서 숫자만 제거

In [8]:
train_input['EMAIL'] = train_input['EMAIL'].str.replace('nia+','')
train_input['EMAIL'] = train_input['EMAIL'].str.replace('@rowan.kr','')
train_target['EMAIL'] = train_target['EMAIL'].str.replace('nia+','')
train_target['EMAIL'] = train_target['EMAIL'].str.replace('@rowan.kr','')

In [9]:
#정렬 및 병합을 위해 EMAIL을 object형에서 int형으로 변경

In [10]:
train_target = train_target.astype({'EMAIL':int})
train_input = train_input.astype({'EMAIL':int})
train_input.dtypes
train_target.dtypes

EMAIL       int32
DIAG_NM    object
dtype: object

In [11]:
#병합을 위해 정렬

In [12]:
train_input = train_input.sort_values('EMAIL')
train_target = train_target.sort_values('EMAIL')

In [13]:
#병합을 위해 DataFrame형식으로 변경

In [14]:
train_input = pd.DataFrame(train_input)
train_target = pd.DataFrame(train_target)

In [15]:
#각각의 병도에 매칭시켜 이메일을 병도로 변경

In [16]:
train_set = pd.merge_asof(train_input, train_target, on='EMAIL')
train_set

,EMAIL,sleep_awake,sleep_bedtime_end,sleep_bedtime_start,sleep_breath_average,sleep_deep,sleep_duration,sleep_efficiency,sleep_hr_5min,sleep_hr_average,...,sleep_score_latency,sleep_score_rem,sleep_score_total,sleep_temperature_delta,sleep_temperature_deviation,sleep_total,CONVERT(sleep_hr_5min USING utf8),CONVERT(sleep_hypnogram_5min USING utf8),CONVERT(sleep_rmssd_5min USING utf8),DIAG_NM
0,3,7590,2020-12-25T08:31:29+09:00,2020-12-25T00:57:29+09:00,16.250,2160,27240,72,...,57.14,...,70,52,55,0.22,0.22,19650,61/59/59/60/61/61/60/61/58/58/59/58/61/61/61/6...,4/4/4/4/2/2/1/4/4/2/2/2/1/1/1/1/2/2/3/3/3/2/2/...,26/21/20/24/33/20/23/19/19/14/16/18/21/26/22/2...,MCI
1,3,7770,2020-12-13T08:16:07+09:00,2020-12-12T22:51:07+09:00,16.375,7710,33900,77,...,59.14,...,75,79,81,-0.16,-0.16,26130,0/62/61/0/60/0/60/59/58/59/59/59/59/59/61/62/6...,4/2/2/2/1/3/1/1/2/2/2/2/2/2/1/1/4/2/2/1/1/1/1/...,0/23/30/0/41/0/28/35/33/28/21/22/22/27/18/16/1...,MCI
2,3,4080,2020-12-14T07:59:31+09:00,2020-12-14T00:20:31+09:00,16.375,4710,27540,85,...,58.04,...,86,75,70,0.17,0.17,23460,0/0/64/63/63/65/67/64/61/61/60/59/59/61/62/61/...,4/4/2/2/4/4/2/2/2/2/2/3/3/1/1/1/1/1/1/3/2/2/2/...,0/0/14/15/15/12/13/12/14/12/13/13/14/19/14/14/...,MCI
3,3,7560,2020-12-15T07:27:31+09:00,2020-12-14T22:54:31+09:00,16.875,5040,30780,75,...,61.36,...,94,72,69,0.16,0.16,23220,0/0/56/56/0/0/0/55/0/0/54/55/56/57/59/60/60/61...,4/2/2/2/2/2/1/1/1/1/2/2/1/1/1/1/1/1/4/2/2/2/2/...,0/0/41/35/0/0/0/57/0/0/54/45/45/48/79/58/58/46...,MCI
4,3,6330,2020-12-18T08:19:33+09:00,2020-12-18T01:09:33+09:00,15.750,2160,25800,75,...,55.20,...,83,63,54,-0.14,-0.14,19470,0/0/0/0/0/55/0/0/0/0/53/53/53/52/53/52/53/53/5...,4/4/2/2/3/3/1/1/4/4/1/2/1/1/2/2/2/1/2/4/2/1/2/...,0/0/0/0/0/25/0/0/0/0/31/26/18/20/24/26/25/17/2...,MCI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9700,475,1740,2021-01-11T06:48:35+09:00,2021-01-11T02:02:35+09:00,15.625,5580,17160,90,...,53.00,...,67,2,37,-1.00,-1.00,15420,53/53/53/53/53/55/57/55/55/55/52/53/53/53/53/5...,4/2/2/1/1/1/1/4/2/2/2/2/2/1/1/1/1/1/4/4/2/2/2/...,48/55/55/60/54/47/44/54/46/41/29/31/37/39/43/3...,CN
9701,475,4620,2021-01-10T09:38:11+09:00,2021-01-10T03:51:11+09:00,14.875,4200,20820,78,...,52.33,...,86,32,40,-0.52,-0.52,16200,0/0/0/55/55/55/55/54/54/55/54/53/55/53/52/52/5...,4/4/4/4/1/1/1/1/1/1/1/2/3/3/2/2/2/2/2/4/4/4/2/...,0/0/0/43/39/40/37/43/37/49/34/49/50/35/48/54/7...,CN
9702,475,2070,2021-01-09T07:44:14+09:00,2021-01-09T02:40:14+09:00,15.250,4860,18240,89,...,53.79,...,91,21,40,-0.08,-0.08,16170,0/0/53/52/53/53/53/54/57/61/59/56/55/57/57/56/...,4/4/4/1/1/1/1/1/1/1/1/3/3/2/4/2/2/1/2/2/2/2/2/...,0/0/34/34/42/39/32/30/39/47/59/53/43/44/40/29/...,CN
9703,475,5610,2020-12-11T07:49:37+09:00,2020-12-11T01:56:37+09:00,14.500,7140,21180,74,...,55.17,...,67,13,38,0.00,0.00,15570,0/0/0/0/0/56/56/58/59/57/56/57/57/57/59/60/60/...,4/4/4/4/4/1/1/1/4/2/2/1/1/1/1/1/1/2/2/2/2/1/1/...,0/0/0/0/0/35/34/36/36/27/31/38/34/31/24/27/28/...,CN
9704,475,4680,2020-12-14T06:43:00+09:00,2020-12-13T23:56:00+09:00,14.375,6930,24420,81,...,55.16,...,89,28,55,-0.58,-0.58,19740,0/0/0/61/60/61/61/61/60/60/62/62/64/65/64/63/5...,4/4/4/4/1/1/1/2/2/1/1/4/2/3/3/4/4/2/2/2/2/2/2/...,0/0/0/46/33/40/39/31/23/29/38/42/35/34/26/19/2...,CN

In [17]:
#이메일에서 병도로 바꾼 열을 target data로 분리

In [18]:
train_target = train_set['DIAG_NM']
train_target

0       MCI
1       MCI
2       MCI
3       MCI
4       MCI
       ...
9700     CN
9701     CN
9702     CN
9703     CN
9704     CN
Name: DIAG_NM, Length: 9705, dtype: object

In [19]:
#input data에 필요없는 'DIAG_NM' , 'EMAIL' 열을 삭제

In [20]:
train_input = train_set.drop(['DIAG_NM', 'EMAIL'], axis=1)
train_input

,sleep_awake,sleep_bedtime_end,sleep_bedtime_start,sleep_breath_average,sleep_deep,sleep_duration,sleep_efficiency,sleep_hr_5min,sleep_hr_average,sleep_hr_lowest,...,sleep_score_efficiency,sleep_score_latency,sleep_score_rem,sleep_score_total,sleep_temperature_delta,sleep_temperature_deviation,sleep_total,CONVERT(sleep_hr_5min USING utf8),CONVERT(sleep_hypnogram_5min USING utf8),CONVERT(sleep_rmssd_5min USING utf8)
0,7590,2020-12-25T08:31:29+09:00,2020-12-25T00:57:29+09:00,16.250,2160,27240,72,...,57.14,52,...,53,70,52,55,0.22,0.22,19650,61/59/59/60/61/61/60/61/58/58/59/58/61/61/61/6...,4/4/4/4/2/2/1/4/4/2/2/2/1/1/1/1/2/2/3/3/3/2/2/...,26/21/20/24/33/20/23/19/19/14/16/18/21/26/22/2...
1,7770,2020-12-13T08:16:07+09:00,2020-12-12T22:51:07+09:00,16.375,7710,33900,77,...,59.14,54,...,65,75,79,81,-0.16,-0.16,26130,0/62/61/0/60/0/60/59/58/59/59/59/59/59/61/62/6...,4/2/2/2/1/3/1/1/2/2/2/2/2/2/1/1/4/2/2/1/1/1/1/...,0/23/30/0/41/0/28/35/33/28/21/22/22/27/18/16/1...
2,4080,2020-12-14T07:59:31+09:00,2020-12-14T00:20:31+09:00,16.375,4710,27540,85,...,58.04,53,...,83,86,75,70,0.17,0.17,23460,0/0/64/63/63/65/67/64/61/61/60/59/59/61/62/61/...,4/4/2/2/4/4/2/2/2/2/2/3/3/1/1/1/1/1/1/3/2/2/2/...,0/0/14/15/15/12/13/12/14/12/13/13/14/19/14/14/...
3,7560,2020-12-15T07:27:31+09:00,2020-12-14T22:54:31+09:00,16.875,5040,30780,75,...,61.36,54,...,62,94,72,69,0.16,0.16,23220,0/0/56/56/0/0/0/55/0/0/54/55/56/57/59/60/60/61...,4/2/2/2/2/2/1/1/1/1/2/2/1/1/1/1/1/1/4/2/2/2/2/...,0/0/41/35/0/0/0/57/0/0/54/45/45/48/79/58/58/46...
4,6330,2020-12-18T08:19:33+09:00,2020-12-18T01:09:33+09:00,15.750,2160,25800,75,...,55.20,52,...,62,83,63,54,-0.14,-0.14,19470,0/0/0/0/0/55/0/0/0/0/53/53/53/52/53/52/53/53/5...,4/4/2/2/3/3/1/1/4/4/1/2/1/1/2/2/2/1/2/4/2/1/2/...,0/0/0/0/0/25/0/0/0/0/31/26/18/20/24/26/25/17/2...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9700,1740,2021-01-11T06:48:35+09:00,2021-01-11T02:02:35+09:00,15.625,5580,17160,90,...,53.00,49,...,95,67,2,37,-1.00,-1.00,15420,53/53/53/53/53/55/57/55/55/55/52/53/53/53/53/5...,4/2/2/1/1/1/1/4/2/2/2/2/2/1/1/1/1/1/4/4/2/2/2/...,48/55/55/60/54/47/44/54/46/41/29/31/37/39/43/3...
9701,4620,2021-01-10T09:38:11+09:00,2021-01-10T03:51:11+09:00,14.875,4200,20820,78,...,52.33,49,...,67,86,32,40,-0.52,-0.52,16200,0/0/0/55/55/55/55/54/54/55/54/53/55/53/52/52/5...,4/4/4/4/1/1/1/1/1/1/1/2/3/3/2/2/2/2/2/4/4/4/2/...,0/0/0/43/39/40/37/43/37/49/34/49/50/35/48/54/7...
9702,2070,2021-01-09T07:44:14+09:00,2021-01-09T02:40:14+09:00,15.250,4860,18240,89,...,53.79,50,...,93,91,21,40,-0.08,-0.08,16170,0/0/53/52/53/53/53/54/57/61/59/56/55/57/57/56/...,4/4/4/1/1/1/1/1/1/1/1/3/3/2/4/2/2/1/2/2/2/2/2/...,0/0/34/34/42/39/32/30/39/47/59/53/43/44/40/29/...
9703,5610,2020-12-11T07:49:37+09:00,2020-12-11T01:56:37+09:00,14.500,7140,21180,74,...,55.17,52,...,58,67,13,38,0.00,0.00,15570,0/0/0/0/0/56/56/58/59/57/56/57/57/57/59/60/60/...,4/4/4/4/4/1/1/1/4/2/2/1/1/1/1/1/1/2/2/2/2/1/1/...,0/0/0/0/0/35/34/36/36/27/31/38/34/31/24/27/28/...
9704,4680,2020-12-14T06:43:00+09:00,2020-12-13T23:56:00+09:00,14.375,6930,24420,81,...,55.16,51,...,74,89,28,55,-0.58,-0.58,19740,0/0/0/61/60/61/61/61/60/60/62/62/64/65/64/63/5...,4/4/4/4/1/1/1/2/2/1/1/4/2/3/3/4/4/2/2/2/2/2/2/...,0/0/0/46/33/40/39/31/23/29/38/42/35/34/26/19/2...

In [21]:
#test data들도 train data와 같이 처리

In [22]:
test_target = test_target.rename(columns={'SAMPLE_EMAIL':'EMAIL'})
test_target
test_input['EMAIL'] = test_input['EMAIL'].str.replace('nia+','')
test_input['EMAIL'] = test_input['EMAIL'].str.replace('@rowan.kr','')
test_target['EMAIL'] = test_target['EMAIL'].str.replace('nia+','')
test_target['EMAIL'] = test_target['EMAIL'].str.replace('@rowan.kr','')
test_target = test_target.astype({'EMAIL':int})
test_input = test_input.astype({'EMAIL':int})
test_input.dtypes
test_target.dtypes
test_input = test_input.sort_values('EMAIL')
test_target = test_target.sort_values('EMAIL')
test_input = pd.DataFrame(test_input)
test_target = pd.DataFrame(test_target)
test_set = pd.merge_asof(test_input, test_target, on='EMAIL')
test_set
test_target = test_set['DIAG_NM']
test_target
test_input = test_set.drop(['DIAG_NM', 'EMAIL'], axis=1)
test_input

,sleep_awake,sleep_bedtime_end,sleep_bedtime_start,sleep_breath_average,sleep_deep,sleep_duration,sleep_efficiency,sleep_hr_5min,sleep_hr_average,sleep_hr_lowest,...,sleep_score_efficiency,sleep_score_latency,sleep_score_rem,sleep_score_total,sleep_temperature_delta,sleep_temperature_deviation,sleep_total,CONVERT(sleep_hr_5min USING utf8),CONVERT(sleep_hypnogram_5min USING utf8),CONVERT(sleep_rmssd_5min USING utf8)
0,2820,2020-12-02T06:21:35+09:00,2020-12-02T00:25:35+09:00,17.125,7890,21360,87,...,51.06,49,...,88,91,13,50,0.06,0.06,18540,0/0/54/54/53/55/54/53/52/52/52/53/52/52/52/52/...,4/4/1/1/1/2/2/1/1/2/1/1/1/1/1/1/1/2/2/2/2/2/2/...,0/0/13/18/16/28/40/58/57/34/32/33/39/32/35/42/...
1,2790,2021-02-02T06:21:40+09:00,2021-02-01T22:51:40+09:00,18.000,8520,27000,90,...,53.88,50,...,95,83,3,73,-0.16,-0.16,24210,56/55/55/54/55/55/55/57/58/57/55/55/55/58/58/5...,4/2/2/1/1/1/1/1/1/2/2/1/1/2/2/1/1/1/2/2/2/2/2/...,36/50/40/36/37/37/36/36/32/42/40/36/37/33/34/3...
2,4230,2020-12-27T07:08:29+09:00,2020-12-27T00:02:29+09:00,17.250,8190,25560,83,...,50.36,46,...,81,91,18,62,0.01,0.01,21330,54/0/53/53/53/53/52/52/53/56/54/54/55/53/54/54...,4/4/4/4/2/2/1/1/1/4/4/2/2/2/4/4/2/2/2/2/2/2/2/...,43/0/53/31/31/28/27/27/36/20/25/26/26/40/32/32...
3,4500,2020-12-26T07:24:31+09:00,2020-12-25T23:22:31+09:00,17.000,7440,28920,84,...,50.12,47,...,81,99,52,74,-0.05,-0.05,24420,54/54/53/53/52/52/53/53/52/51/50/50/49/49/49/5...,4/4/2/2/2/2/4/4/2/2/2/1/1/1/1/1/1/1/1/2/3/2/2/...,36/35/39/42/33/32/34/32/39/20/28/28/41/45/49/5...
4,1650,2020-12-25T07:11:47+09:00,2020-12-25T00:15:47+09:00,17.250,8160,24960,93,...,51.52,48,...,99,72,47,70,0.21,0.21,23310,54/53/53/55/54/54/53/53/56/57/56/53/55/54/54/5...,4/2/1/1/2/2/1/1/1/1/2/2/2/3/4/2/2/2/2/1/1/2/2/...,30/30/35/27/37/26/26/29/21/30/33/30/30/38/29/2...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2473,5070,2021-01-26T07:40:09+09:00,2021-01-26T01:06:09+09:00,15.125,7410,23640,79,...,53.85,48,...,69,78,37,50,-0.13,-0.13,18570,0/51/51/51/52/50/49/49/49/49/48/48/48/48/48/49...,4/2/2/2/2/2/2/2/2/2/1/1/1/1/1/1/1/1/1/2/1/1/2/...,0/21/37/39/33/44/39/47/26/27/31/27/26/25/24/25...
2474,2430,2021-01-27T08:09:20+09:00,2021-01-27T00:20:20+09:00,15.500,7170,28140,91,...,51.63,49,...,97,67,98,80,0.34,0.34,25710,0/49/50/56/0/50/49/49/49/49/49/49/50/54/54/52/...,2/2/2/4/2/2/1/1/1/1/1/1/1/1/1/1/1/4/4/2/2/2/2/...,0/40/43/45/0/24/22/27/27/23/21/20/22/18/19/21/...
2475,4800,2021-01-28T07:08:42+09:00,2021-01-27T23:56:42+09:00,15.500,7050,25920,81,...,52.04,49,...,74,70,47,61,0.07,0.07,21120,0/55/0/54/54/53/53/53/52/52/50/50/51/52/54/52/...,4/2/2/2/2/2/2/2/1/1/1/1/1/2/2/2/2/2/2/2/2/2/2/...,0/36/0/28/35/36/37/51/42/76/51/42/30/41/46/57/...
2476,2910,2021-01-30T08:40:09+09:00,2021-01-30T00:27:09+09:00,14.500,5610,29580,90,...,50.76,46,...,95,81,95,84,0.57,0.57,26670,0/57/59/58/56/55/54/53/53/52/53/52/53/53/52/52...,4/2/2/1/2/2/2/1/2/2/2/2/3/2/2/1/2/2/2/4/2/2/2/...,0/22/28/26/28/23/44/72/40/36/39/52/34/31/33/32...
2477,4170,2020-12-27T08:05:50+09:00,2020-12-27T01:19:50+09:00,14.000,7140,24360,83,...,51.37,48,...,79,94,45,57,-0.02,-0.02,20190,0/0/0/0/51/55/51/49/48/49/48/48/49/49/49/49/51...,4/4/4/2/2/2/2/2/1/1/1/1/1/1/1/1/1/1/1/2/2/4/3/...,0/0/0/0/32/44/29/23/24/21/25/20/23/20/22/22/26...

In [23]:
#현재는 처리방법을 찾지 못한 object 변수들을 제거 -> 후에 처리방법을 알아봐도 좋을듯함

In [28]:
test_input = test_input.drop(['sleep_bedtime_end','sleep_bedtime_start','sleep_hr_5min','sleep_hypnogram_5min','sleep_rmssd_5min','CONVERT(sleep_hr_5min USING utf8)','CONVERT(sleep_hypnogram_5min USING utf8)','CONVERT(sleep_rmssd_5min USING utf8)'], axis=1)
test_input.dtypes

sleep_awake                      int64
sleep_breath_average           float64
sleep_deep                       int64
sleep_duration                   int64
sleep_efficiency                 int64
sleep_hr_average               float64
sleep_hr_lowest                  int64
sleep_is_longest                 int64
sleep_light                      int64
sleep_midpoint_at_delta          int64
sleep_midpoint_time              int64
sleep_onset_latency              int64
sleep_period_id                  int64
sleep_rem                        int64
sleep_restless                   int64
sleep_rmssd                      int64
sleep_score                      int64
sleep_score_alignment            int64
sleep_score_deep                 int64
sleep_score_disturbances         int64
sleep_score_efficiency           int64
sleep_score_latency              int64
sleep_score_rem                  int64
sleep_score_total                int64
sleep_temperature_delta        float64
sleep_temperature_deviation    float64
sleep_total                      int64
dtype: object

In [29]:
test_target.dtypes

dtype('O')

In [30]:
train_target.dtypes

dtype('O')

In [32]:
train_input = train_input.drop(['sleep_bedtime_end','sleep_bedtime_start',
'sleep_hr_5min','sleep_hypnogram_5min','sleep_rmssd_5min','CONVERT(sleep_hr_5min USING utf8)','CONVERT(sleep_hypnogram_5min USING utf8)','CONVERT(sleep_rmssd_5min USING utf8)'], axis=1)
train_input.dtypes

sleep_awake                      int64
sleep_breath_average           float64
sleep_deep                       int64
sleep_duration                   int64
sleep_efficiency                 int64
sleep_hr_average               float64
sleep_hr_lowest                  int64
sleep_is_longest                 int64
sleep_light                      int64
sleep_midpoint_at_delta          int64
sleep_midpoint_time              int64
sleep_onset_latency              int64
sleep_period_id                  int64
sleep_rem                        int64
sleep_restless                   int64
sleep_rmssd                      int64
sleep_score                      int64
sleep_score_alignment            int64
sleep_score_deep                 int64
sleep_score_disturbances         int64
sleep_score_efficiency           int64
sleep_score_latency              int64
sleep_score_rem                  int64
sleep_score_total                int64
sleep_temperature_delta        float64
sleep_temperature_deviation    float64
sleep_total                      int64
dtype: object

In [ ]:
#로지스틱 회귀 모델 적용 (60,70% 정확도로 전체적인 과소적합, 제대로 된 모델을 찾아야함)

In [39]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr = LogisticRegression(C=20, max_iter=10000)
lr.fit(train_input, train_target)

print(lr.score(train_input, train_target))
print(lr.score(test_input, test_target))

0.6132921174652242
0.7231638418079096

C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [ ]:
#경사하강법분류모델도 정확도가 아직 높지않음

In [34]:
from sklearn.linear_model import SGDClassifier

In [38]:
sc = SGDClassifier(loss='log_loss', max_iter=10000, random_state=42)
sc.fit(train_input, train_target)

print(sc.score(train_input, train_target))
print(sc.score(test_input, test_target))

0.5868109222050489
0.6969330104923325